set -as terminal-overrides ',xterm*:RGB'

# Allow terminal escape sequence passthrough (needed for kitty graphics)
set -g allow-passthrough on

# Unbind the default prefix
unbind C-b

# Set new prefix to Ctrl+Space
set -g prefix C-Space

# Bind Ctrl+Space again to send prefix to nested tmux or other programs
bind C-Space send-prefix

set -ga update-environment TERM
set -ga update-environment TERM_PROGRAM

set-environment -g EDITOR nvim
set-environment -g VISUAL nvim

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Pane colors
set -g pane-border-style "fg=#AF5FAF"
set -g pane-active-border-style "fg=#AF5FAF"

# tmux copy mode
set-window-option -g mode-keys vi
bind v copy-mode

# keybindings
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'ofirgall/tmux-window-name'
set -g @plugin 'TechnicalDC/tmux-pywal-theme'

# tmux-window-name options
set -g @tmux_window_name_shells "['bash', 'fish', 'sh', 'zsh']"
set -g @tmux_window_dir_programs "['nvim', 'vim', 'vi', 'git']"
set -g @tmux_window_name_use_tilde "True"

set -g mouse on       
unbind -n WheelUpPane
unbind -n WheelDownPane

#Status bar position
set-option -g status-position top
set-option -g status on

# Integrate vim keys to swtich in and out of vim panes
 is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
     | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
 bind-key -n C-h  if-shell  "$is_vim"  "send-keys C-h"  "select-pane -L"
 bind-key -n C-j   if-shell  "$is_vim"  "send-keys C-j"   "select-pane -D"
 bind-key -n C-k  if-shell  "$is_vim"  "send-keys C-k"  "select-pane -U"
 bind-key -n C-l   if-shell  "$is_vim"  "send-keys C-l"   "select-pane -R"

# Use Ctrl + Arrow Keys for resizing panes in 5-unit increments
bind -n C-Up resize-pane -U 5
bind -n C-Down resize-pane -D 5
bind -n C-Left resize-pane -L 5
bind -n C-Right resize-pane -R 5

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
