# ---------- Window ----------
window_padding_width 5
background_opacity 1.0


# ---------- Font ----------
font_size 15.0
baseline -2


# ---------- Selection ----------
copy_on_select yes

# ---------- Cursor ----------
cursor_blink_interval 0.5
cursor_shape block

shell btop -c /home/duck/.config/btop/btop.conf
